application: google.com:angulardart
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "10m"

libraries:
  - name: webapp2
    version: latest

  - name: jinja2
    version: latest

  - name: markupsafe
    version: latest

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: app/static/css

- url: /dart
  static_dir: app/static/dart

- url: /js
  static_dir: app/static/js

- url: /img
  static_dir: app/static/img

- url: /.*
  script: routes.app